TCL_Taxi_Analysis:
  outputs:
    dev:
      type: duckdb
      path: D:\Projects\Taxi_Analysis\taxi_nyc.db
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
  snapshots:
      type: duckdb
      path: D:\Projects\Taxi_Analysis\taxi_nyc.db  # Specify the path to your snapshots database
  target: dev
